language: cpp

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - BASE_REPO=rweickelt/qbs
    - BASE_TAG=1.10.1
    - DEPLOY_REPO=rweickelt/qt

  matrix:
    - TARGET=mingw-w64
    - TARGET=linux-x86_64

install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull $BASE_REPO:$BASE_TAG

script:
  - docker build -f $TARGET.docker -t docker-image:$COMMIT .
  - docker run -v ${PWD}/test:/test docker-image:$COMMIT
        build --file /test/hello-world.qbs release profile:qt5

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag docker-image:$COMMIT $DEPLOY_REPO:$TAG-$TARGET
  - docker push DEPLOY_REPO
