language: cpp

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=rweickelt/qt

  matrix:
    - TARGET=mingw-w64
    - TARGET=linux-x86_64

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - docker build -f $TARGET.docker -t docker-image .
  - docker run -v ${PWD}/test:/test docker-image
        build --file /test/hello-world.qbs release profile:qt5

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag docker-image $REPO:$TAG-$TARGET
  - docker push $REPO
