language: cpp

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  matrix:
    - TARGET=mingw-w64

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull rweickelt/qbs:1.9.1-1

script:
  - docker build -f mingw-w64.docker -t docker-image .
  - docker run -v ${PWD}/test:/test docker-image
        build --file /test/hello-world.qbs release profile:qt5

after_success:
  - docker tag docker-image $DOCKER_USERNAME/qt
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker push rweickelt/qt:$TARGET-$TAG